config/routes.rb
Rails.application.routes.draw do
  resources :breeds

  root "breeds#index"

end

app/models/breed.rb
class Breed < ActiveRecord::Base
  validates_presence_of :name, :pic_url
  validates_uniqueness_of :name, :pic_url

  before_validation :verify_breed

  private

  def verify_breed
    begin
      response = JSON.parse(RestClient.get("https://dog.ceo/api/breed/#{name}/images").body)
      self.pic_url = response["message"].first
    rescue Object => e
      errors.add(:name, 'No breed found with this name')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController

  def index
    @breeds = Breed.order('name ASC')
  end

  def new
    @breed = Breed.new
  end

  def create
    @breed = Breed.new breed_params
    if @breed.valid?
      @breed.save
      flash[:success] = 'Breed has been successfully found and saved!'
      redirect_to breeds_path
    else
      flash[:errors] = @breed.errors.full_messages
      render :new
    end
  end

  def show
    @breed = Breed.find params[:id]
  end


  private
  def breed_params
    params.require(:breed).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/views/breeds/index.html.erb
<div class="dog">

  <h1>Current Breeds in System</h1>
  <%=link_to 'New', new_breed_path%>

  <table style="width:100%">
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Action</th>
    </tr>
    <%@breeds.each_with_index do |breed, index|%>
        <tr>
          <td><%= index%></td>
          <td><%= breed.name.humanize %></td>
          <td><%= link_to 'Details', breed_path(breed)%></td>
        </tr>
        <h3></h3>
    <%end%>
  </table>

</div>

app/views/breeds/new.html.erb
<%= link_to 'Back', breeds_path%>
<p style="color: red;font-size: 12px;"><%= flash[:errors].join(', ') if flash[:errors]%></p>

<hr/>
<h2>Create & Find New Breed</h2>
<%= form_for @breed do |f|%>
    <%= f.text_field :name%>
    <%= f.submit%>
<%end%>

app/views/breeds/show.html.erb
<div class="dog">

  <h1>It's a <%= @breed.name.humanize %></h1>

  <%= link_to 'Back', breeds_path%>
  <h3><%= @breed.name.humanize %></h3>

  <%= image_tag @breed.pic_url %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTestProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>